---
name: "Предложение нового функционала"
description: "Форма для запроса на создание нового функционала в дизайн-системе"
title: "[ФУНКЦИОНАЛ] "
labels:
  - "type/feature"
  - "status/needs-triage"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Используйте формат: [тип]:[назначение]**
        Например: "Компонент ProgressStepper: для отображения многошагового процесса" или "Утилита formatDate: для форматирования дат"
        Форма предназначена для сбора информации о необходимости создания нового функционала в дизайн-системе.
        **Перед созданием нового функционала, убедитесь что:**
        - Аналогичный функционал не существует в системе
        - Задачу нельзя решить с помощью существующих инструментов

  - type: textarea
    id: component_add
    attributes:
      label: "Что предлагается добавить"
      description: "Опишите что именно предлагается добавить (компонент, утилита, хук, стиль, токен и т.д.)"
      placeholder: "Например: Компонент для отображения прогресса загрузки файлов с возможностью отмены и показом скорости загрузки, или Утилита для валидации email-адресов с поддержкой международных доменов"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: component_result
    attributes:
      label: "Ожидаемый результат"
      description: "Какой результат ожидается от нового функционала"
      placeholder: "Например: Разработчики смогут единообразно валидировать email-адреса во всех формах приложения, что снизит количество ошибок и ускорит разработку"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: component_reason
    attributes:
      label: "Причина необходимости"
      description: "Почему возникла необходимость в новом функционале"
      placeholder: "Например: В текущих проектах часто требуется отображать прогресс многошаговых процессов (регистрация, оформление заказа, настройка профиля), но существующие компоненты не покрывают эту потребность"
      render: markdown
    validations:
      required: true

  - type: input
    id: design_prototype
    attributes:
      label: "Ссылка на дизайн-файл или документацию"
      description: "Приложите ссылку на прототип, спецификацию или документацию"
      placeholder: "https://figma.com/file/... или https://docs.google.com/..."
    validations:
      required: false

  - type: textarea
    id: primary_use_case
    attributes:
      label: "Основной сценарий использования"
      description: "Опишите главный сценарий использования новой фичи"
      placeholder: |
        Пример: Компонент Button используется для создания интерактивных кнопок в формах и интерфейсах.
        - Отправка форм
        - Навигация между страницами
        - Вызов модальных окон
        - Подтверждение действий пользователя
      render: markdown
    validations:
      required: false

  - type: textarea
    id: secondary_use_cases
    attributes:
      label: "Дополнительные сценарии фичи"
      description: "Опишите дополнительные варианты использования новой фичи"
      placeholder: |
        Пример: Дополнительные сценарии для Button:
        - Использование как toggle-кнопка
        - Группировка кнопок в toolbar
      render: markdown
    validations:
      required: false
---
