---
name: "🐞 Исправление бага"
description: "Сообщение о проблемах в существующих компонентах дизайн-системы"
title: "[БАГ] "
labels: ["type/bug", "status/needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Используйте формат: [компонент]:[описание проблемы]**
        Например: "Dropdown: не закрывается при клике вне области компонента"
        
        Форма предназначена для сбора информации с воспроизведением этапов бага, что сокращает время на диагностику и исправление проблем.
        **Перед созданием баг репорта:**
        - Убедитесь, что используете последнюю версию компонента
        - Проверьте, не был ли уже создан похожий bug report
        - Подготовьте шаги для воспроизведения проблемы

  - type: input
    id: component
    attributes:
      label: "Компонент с багом"
      description: "Укажите название компонента, в котором обнаружена проблема"
      placeholder: "Например: Button, Select, DataTable..."
    validations:
      required: true

  - type: textarea
    id: bug_summary
    attributes:
      label: "Краткое описание бага"
      description: "Опишите суть проблемы в нескольких предложениях (Ожидаемое поведение, фактическое поведение)"
      placeholder: "Краткое описание сути проблемы"
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Последовательность действий для воспроизведения"
      description: "Пошаговые инструкции для воспроизведения проблемы"
      placeholder: |
        1. Первый шаг
        2. Второй шаг
        3. Третий шаг
      render: markdown
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: "Окружение"
      description: "Укажите информацию об окружении: браузер, ОС, устройство, версии фреймворка и зависимостей"
      placeholder: |
        Браузер: Chrome 96.0.4664.110
        ОС: macOS Monterey 12.1
        Устройство: Desktop
        Фреймворк: React 18.2.0
        Зависимости: Next.js 13.0.0, TypeScript 4.8.0
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Воспроизведение проблемы"
      description: "Предоставьте минимальный код, скриншоты или ссылку на живую демонстрацию (CodeSandbox, CodePen, Stackblitz)"
      placeholder: |
        Минимальный пример кода ссылкой на CodeSandbox/CodePen/Stackblitz и любые соответствующие сообщения об ошибках из консоли браузера
      render: markdown
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: "Временное решение (workaround)"
      description: "Если знаете способ обойти проблему, опишите его"
      placeholder: "Опишите временное решение если оно существует"
      render: markdown
---
