name: 🚀 Auto Create in Satellite

on:
  issues:
    types: [labeled]

jobs:
  auto-create-satellite-issue:
    runs-on: ubuntu-latest
    if: startsWith(github.event.label.name, 'satellite/')
    
    steps:
      - name: Checkout Hub
        uses: actions/checkout@v4

      - name: Auto create issue in satellite
        uses: actions/github-script@v7
        with:
          script: |
            const { issue, label } = context.payload;
            
            // Проверяем что это satellite метка
            if (!label.name.startsWith('satellite/')) return;
            
            const satelliteName = label.name.replace('satellite/', '');
            
            console.log(`🔄 Auto-creating issue in satellite: ${satelliteName}`);
            
            // Проверяем что задача еще не создана в satellite
            const hasRoutedLabel = issue.labels.some(l => l.name === 'status/routed');
            if (hasRoutedLabel) {
              console.log('ℹ️ Issue already routed to satellite, skipping');
              return;
            }
            
            await createSatelliteIssue(issue, satelliteName);
            
            async function createSatelliteIssue(hubIssue, satelliteName) {
              try {
                // Маппинг satellites на репозитории
                const repoMap = {
                  'yandex-test': 'yandex-test',
                  'ozon-test': 'ozon-test',
                  'wildberries-test': 'wildberries-test'
                };
                
                const targetRepo = repoMap[satelliteName];
                
                if (!targetRepo) {
                  console.log(`❌ Unknown satellite: ${satelliteName}`);
                  return;
                }
                
                // Используем PAT для доступа к satellite
                const { Octokit } = require('@octokit/rest');
                const octokit = new Octokit({
                  auth: '${{ secrets.SYNC_ACCESS_TOKEN }}'
                });
                
                // Создаем issue в satellite
                const satelliteIssue = await octokit.rest.issues.create({
                  owner: context.repo.owner,
                  repo: targetRepo,
                  title: `[From Hub] ${hubIssue.title}`,
                  body: `## 📡 Задача создана из Hub
                  
                **Original Issue**: #${hubIssue.number}
                **Hub URL**: ${hubIssue.html_url}
                **Created By**: @${hubIssue.user.login}
                **Satellite**: ${satelliteName}
                **Auto-created**: ${new Date().toISOString()}

                ---
                
                ${hubIssue.body}
                
                ---
                
                # ### 🔗 Связь с Hub
                # - Все обсуждения и планирование в [Hub Issue #${hubIssue.number}](${hubIssue.html_url})
                # - Код и реализация в этом репозитории
                # - При создании PR ссылайтесь на эту задачу
                # - Статус синхронизируется автоматически
                #   `,
                #   labels: ['from-hub', 'needs-triage']
                # });
                
                # // Обновляем метки в Hub
                # await github.rest.issues.removeLabel({
                #   owner: context.repo.owner,
                #   repo: context.repo.repo,
                #   issue_number: hubIssue.number,
                #   name: 'status/needs-routing'
                # });
                
                # await github.rest.issues.addLabels({
                #   owner: context.repo.owner,
                #   repo: context.repo.repo,
                #   issue_number: hubIssue.number,
                #   labels: ['status/routed', 'auto-created']
                # });
                
                // Добавляем комментарий с ссылкой
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: hubIssue.number,
                  body: `✅ **Задача автоматически создана в satellite!**
                  
                **Satellite**: \`${targetRepo}\`
                **Issue**: [#${satelliteIssue.data.number}](${satelliteIssue.data.html_url})
                **Auto-created**: ${new Date().toLocaleString()}
                
                **Статус**: 🟢 Активно в satellite`
                                });
                
                console.log(`✅ Created issue in ${targetRepo}: #${satelliteIssue.data.number}`);
                
              } catch (error) {
                console.log(`❌ Failed to create in ${satelliteName}: ${error.message}`);
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: hubIssue.number,
                  body: `❌ **Ошибка автосоздания в satellite**
                  
              Не удалось создать задачу в satellite \`${satelliteName}\`:
              \`\`\`
              ${error.message}
              \`\`\``
                });
              }
            }
