name: 🚀 Auto Create in Satellite

on:
  issues:
    types: [labeled]

jobs:
  auto-create-satellite-issue:
    runs-on: ubuntu-latest
    if: startsWith(github.event.label.name, 'satellite/')
    
    steps:
      - name: Checkout Hub
        uses: actions/checkout@v4

      - name: Auto create issue in satellite
        uses: actions/github-script@v7
        env:
          SYNC_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        with:
          script: |
            const { issue, label } = context.payload;
            
            if (!label.name.startsWith('satellite/')) return;
            
            const satelliteName = label.name.replace('satellite/', '');
            console.log('🔄 Auto-creating issue in satellite: ' + satelliteName);
            
            const hasRoutedLabel = issue.labels.some(l => l.name === 'state/routed');
            if (hasRoutedLabel) {
              console.log('ℹ️ Issue already routed to satellite, skipping');
              return;
            }
            
            await createSatelliteIssue(issue, satelliteName);
            
            async function createSatelliteIssue(hubIssue, satelliteName) {
              try {
                const repoMap = {
                  'yandex-test': 'yandex-test',
                  'ozon': 'ozon-test',
                  'wildberries-test': 'wildberries-test',
                  'yandex': 'yandex',
                  'ozon': 'ozon',
                  'wildberries': 'wildberries',
                  'wordpress': 'wordpress',
                  'cdek-it.github.io': 'cdek-it.github.io',
                  'xstate-json-types': 'xstate-json-types',
                  'widget': 'widget',
                  'sdk2.0': 'sdk2.0',
                  'opencart': 'opencart',
                  'react-ui-kit': 'react-ui-kit',
                  'vue-ui-kit': 'vue-ui-kit',
                  'react-native-ui-kit': 'react-native-ui-kit',
                  'angular-ui-kit': 'angular-ui-kit'
                };
                
                const targetRepo = repoMap[satelliteName];
                if (!targetRepo) {
                  console.log('❌ Unknown satellite: ' + satelliteName);
                  return;
                }

                const labelsToSync = hubIssue.labels
                  .map(l => l.name)
                  .filter(labelName => 
                    !labelName.startsWith('satellite/') &&
                    labelName !== 'status/need-triage'
                  );
                
                // Используем fetch для создания issue
                const response = await fetch(`https://api.github.com/repos/${context.repo.owner}/${targetRepo}/issues`, {
                  method: 'POST',
                  headers: {
                    'Authorization': `token ${process.env.SYNC_TOKEN}`,
                    'Content-Type': 'application/json',
                    'Accept': 'application/vnd.github.v3+json'
                  },
                  body: JSON.stringify({
                    title: '[From Hub] ' + hubIssue.title,
                    body: '## 📡 Задача создана из Hub\n\n' +
                          '**Original Issue**: #' + hubIssue.number + '\n' +
                          '**Hub URL**: ' + hubIssue.html_url + '\n' +
                          '**Created By**: @' + hubIssue.user.login + '\n' +
                          '**Satellite**: ' + satelliteName + '\n' +
                          '**Auto-created**: ' + new Date().toISOString() + '\n\n' +
                          '---\n\n' +
                          hubIssue.body + '\n\n' +
                          '---\n\n' +
                          '### 🔗 Связь с Hub\n' +
                          '- Все обсуждения и планирование в [Hub Issue #' + hubIssue.number + '](' + hubIssue.html_url + ')\n' +
                          '- Код и реализация в этом репозитории\n' +
                          '- При создании PR ссылайтесь на эту задачу\n' +
                          '- Статус синхронизируется автоматически',
                    labels: ['state/from-hub', 'status/needs-triage', ...labelsToSync]
                  })
                });
                
                if (!response.ok) {
                  throw new Error(`HTTP error! status: ${response.status} - ${await response.text()}`);
                }
                
                const satelliteIssue = await response.json();
                
                // Обновляем описание Hub issue вместо создания комментария
                const updatedBody = hubIssue.body + '\n\n---\n\n' +
                  '## 📡 Satellite Information\n\n' +
                  '✅ **Задача автоматически создана в satellite!**\n\n' +
                  '**Satellite**: `' + targetRepo + '`\n' +
                  '**Satellite Issue**: [#' + satelliteIssue.number + '](' + satelliteIssue.html_url + ')\n' +
                  '**Auto-created**: ' + new Date().toLocaleString() + '\n' +
                  '**Статус**: 🟢 Активно в satellite';
                
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: hubIssue.number,
                  body: updatedBody
                });
                
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: hubIssue.number,
                  labels: ['state/routed']
                });
                
                console.log('✅ Created issue in ' + targetRepo + ': #' + satelliteIssue.number);
                
              } catch (error) {
                console.log('❌ Failed to create in ' + satelliteName + ': ' + error.message);
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: hubIssue.number,
                  body: '❌ **Ошибка автосоздания в satellite**\n\n' +
                        'Не удалось создать задачу в satellite `' + satelliteName + '`:\n' +
                        '```\n' + error.message + '\n```'
                });
              }
            }
