name: 🏷️ Issues Auto Label

on:
  issues:
    types: [opened]

jobs:
  simple-auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simple auto labeling
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Проверяем наличие конфиг файла
            if (!fs.existsSync('./.github/labels-config.json')) {
              console.log('❌ labels-config.json not found');
              return;
            }
            
            // Загружаем конфиг
            const config = require('./.github/labels-config.json');
            const issue = context.payload.issue;
            
            console.log('🔍 Analyzing issue: ' + issue.title);
            
            const title = issue.title.toLowerCase();
            const body = issue.body ? issue.body.toLowerCase() : '';
            const text = title + ' ' + body;
            
            const existingLabels = issue.labels.map(label => label.name);
            const labelsToAdd = [];
            
            // Добавляем метки по умолчанию
            if (config.rules && config.rules.default_labels) {
              config.rules.default_labels.forEach(label => {
                if (!existingLabels.includes(label)) {
                  labelsToAdd.push(label);
                }
              });
            }
            
            // Ищем совпадения ключевых слов
            for (const categoryName in config.labels) {
              const categoryLabels = config.labels[categoryName];
              if (Array.isArray(categoryLabels)) {
                for (const labelDef of categoryLabels) {
                  if (labelDef.keywords && !existingLabels.includes(labelDef.name)) {
                    let found = false;
                    for (const keyword of labelDef.keywords) {
                      if (text.includes(keyword.toLowerCase())) {
                        found = true;
                        break;
                      }
                    }
                    if (found && !labelsToAdd.includes(labelDef.name)) {
                      labelsToAdd.push(labelDef.name);
                      console.log('✅ Added label: ' + labelDef.name);
                    }
                  }
                }
              }
            }
            
            // Применяем метки если есть новые
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labelsToAdd
              });
              
              console.log('🎯 Labels applied: ' + labelsToAdd.join(', '));
              
              // Простой комментарий
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '🏷️ Automatically added labels: ' + labelsToAdd.map(l => '`' + l + '`').join(', ')
              });
            } else {
              console.log('ℹ️ No new labels to add');
            }
