name: 🏷️ Auto Label from Config

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto-label from labels-config.json
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Загружаем конфиг меток
            if (!fs.existsSync('./.github/labels-config.json')) {
              console.log('❌ labels-config.json not found');
              return;
            }
            
            const config = require('./.github/labels-config.json');
            const { issue, pull_request } = context.payload;
            const item = issue || pull_request;
            
            if (!item) return;
            
            console.log(`🔍 Analyzing: "${item.title}"`);
            
            const title = item.title.toLowerCase();
            const body = item.body?.toLowerCase() || '';
            const text = title + ' ' + body;
            
            const existingLabels = item.labels.map(label => label.name);
            const labelsToAdd = new Set();
            
            // Добавляем метки по умолчанию из конфига
            if (config.rules && config.rules.default_labels) {
              config.rules.default_labels.forEach(label => {
                if (!existingLabels.includes(label)) {
                  labelsToAdd.add(label);
                }
              });
            }
            
            // Анализируем ключевые слова из всех категорий меток
            for (const [categoryName, categoryLabels] of Object.entries(config.labels)) {
              if (!Array.isArray(categoryLabels)) continue;
              
              for (const labelDef of categoryLabels) {
                // Пропускаем если метка уже есть или нет ключевых слов
                if (existingLabels.includes(labelDef.name) || !labelDef.keywords) continue;
                
                // Проверяем ключевые слова
                const keywordMatches = labelDef.keywords.filter(keyword => 
                  text.includes(keyword.toLowerCase())
                ).length;
                
                // Проверяем порог уверенности
                const confidenceThreshold = config.rules?.confidence_threshold || 1;
                
                if (keywordMatches >= confidenceThreshold) {
                  console.log(`✅ ${labelDef.name}: ${keywordMatches} keyword matches`);
                  labelsToAdd.add(labelDef.name);
                  
                  // Для приоритетов и типов - добавляем только одну метку из категории
                  if (categoryName === 'priorities' || categoryName === 'types') {
                    break;
                  }
                }
              }
            }
            
            // Применяем метки
            const newLabels = [...labelsToAdd].filter(label => !existingLabels.includes(label));
            
            if (newLabels.length > 0) {
              console.log(`🎯 Adding labels: ${newLabels.join(', ')}`);
              
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: item.number,
                labels: newLabels
              });
              
              await createLabelingComment(item.number, newLabels, config);
            }
            
            async function createLabelingComment(issueNumber, newLabels, config) {
              const labelDetails = newLabels.map(label => {
                // Находим описание метки в конфиге
                for (const category of Object.values(config.labels)) {
                  if (Array.isArray(category)) {
                    const labelDef = category.find(l => l.name === label);
                    if (labelDef) {
                      return `• **${label}** - ${labelDef.description}`;
                    }
                  }
                }
                return `• ${label}`;
              }).join('\n');
              
              const comment = `🏷️ **Автоматически назначены метки**:
              
# ${labelDetails}

# **Как это работает?**
# - Система анализирует текст задачи и сопоставляет с ключевыми словами из labels-config.json
# - Метки назначаются автоматически на основе найденных ключевых слов
# - Если метки не подходят - измените их вручную

# _Проанализировано ${text.length} символов_`;
              
#               await github.rest.issues.createComment({
#                 owner: context.repo.owner,
#                 repo: context.repo.repo,
#                 issue_number: issueNumber,
#                 body: comment
#               });
#             }
